spring:

  data:
    mongodb:
      database: practice
      uri: mongodb+srv://ferrylinton:kkFNbwQA1PFF5opi@cluster0.zf0pd.mongodb.net/test?authSource=admin&replicaSet=atlas-1dfm52-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
  
  liquibase:
    enabled: true
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
server:
  port: 8080
  
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG