spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:./h2db/simpledb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  
  data:
    web:
      pageable:
        default-page-size: 10
  
  liquibase:
    enabled: true
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
server:
  port: 8080