spring:
  application:
    name: Spring-Redis-Reactive

  # Redis DB configuration
  redis:
    host: localhost
    port: 6379
    password: password

# Server configuration
server:
  port: 8080

# Logging settings
logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.springframework.data.redis: DEBUG

