pbkdf2password:
  secret: mysecret
  iteration: 33
  keylength: 256

jwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 28800

spring:
  
  liquibase:
    enabled: true
    url: jdbc:h2:./h2db/simpledb;MODE=PostgreSQL;IGNORECASE=TRUE
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
    
  r2dbc:
    url: r2dbc:h2:file:///./h2db/simpledb;MODE=PostgreSQL;IGNORECASE=TRUE
    username: sa
    password: password
  
  data:
    web:
      pageable:
        default-page-size: 10
      
server:
  port: 8080
  
logging:
  level:
    io.r2dbc.h2.client.SessionClient: TRACE